//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace php.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public long AgentNumber { get; set; }
        public string City { get; set; }
        public string ImageURL { get; set; }
        public Nullable<long> LicenseNo { get; set; }
        public string VirtualCardURL { get; set; }
    }
}
