//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace php.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long UserRoleId { get; set; }
        public long AccountId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long UserRoleTypeId { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
